"""emails table

Revision ID: 11b27ba6933c
Revises: 3147cdef1e3c
Create Date: 2021-11-07 09:46:56.530795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b27ba6933c'
down_revision = '3147cdef1e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Email', sa.Column('fromid', sa.Integer(), nullable=False))
    op.drop_column('Email', 'fromemail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Email', sa.Column('fromemail', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('Email', 'fromid')
    # ### end Alembic commands ###
