"""emails table

Revision ID: 3147cdef1e3c
Revises: 5dca8fc35672
Create Date: 2021-11-07 09:39:13.177183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3147cdef1e3c'
down_revision = '5dca8fc35672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Email', sa.Column('to', sa.String(length=50), nullable=False))
    op.drop_column('Email', 'toid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Email', sa.Column('toid', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('Email', 'to')
    # ### end Alembic commands ###
