"""emails table

Revision ID: 4a509519f36e
Revises: fb4a6b3702d9
Create Date: 2021-11-07 09:17:58.280691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a509519f36e'
down_revision = 'fb4a6b3702d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Email', sa.Column('subject', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Email', 'subject')
    # ### end Alembic commands ###
