"""emails table

Revision ID: 5dca8fc35672
Revises: 4a509519f36e
Create Date: 2021-11-07 09:27:03.803235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dca8fc35672'
down_revision = '4a509519f36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Email', sa.Column('fromemail', sa.String(length=50), nullable=False))
    op.drop_column('Email', 'fromid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Email', sa.Column('fromid', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('Email', 'fromemail')
    # ### end Alembic commands ###
