"""emails table

Revision ID: 7bc89589e9cd
Revises: 11b27ba6933c
Create Date: 2021-11-07 09:53:17.829393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc89589e9cd'
down_revision = '11b27ba6933c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Email', sa.Column('fromemail', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Email', 'fromemail')
    # ### end Alembic commands ###
